### ISSUE TITLE
Exceptions when searching in the website

### ISSUE THREAD

**Issue by blmhemu** [kubesail/kubesail-agent#14]
Sorry to post it here. But I did not find where to raise the issue.

![image](https://user-images.githubusercontent.com/19410501/93014385-510b8900-f5ce-11ea-976e-3e1c4870ebcc.png)

Getting the above exception when searching for a template (May be non-existant one ??)

**Comment by erulabs** [comment]
Hey @blmhemu - We're rolling out a patch for this currently - Thanks for reporting this!
